backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts
